language: python
python:
  - "3.7"
before_install:
  - pip uninstall ansible
install:
  - pip3 install ansible
  - pip install git+https://github.com/ansible/ansible-lint.git
script:
  - ansible-lint main.yml -x 204,207,208,301,303,305,306,401,601,602
