- hosts: localhost
  tasks:
      - name: add undercloud_host to inventory file
        add_host:
            name: "{{ groups.undercloud|first }}"
            ansible_user: "stack"

- hosts: undercloud
  become: yes
  become_user: stack
  vars:
      browbeat_dir: "/home/stack/browbeat"
  tasks:
    - name: clone browbeat
      git:
          repo: "https://github.com/cloud-bulldozer/browbeat.git"
          dest: "{{ browbeat_dir }}"
          force: yes
    - name: get dns server
      shell: |
          cat /etc/resolv.conf | grep nameserver | head -n1 | cut -d ' ' -f2
      register: dns_server
    - name: replace dns_server in groups vars
      shell: |
          sed -i 's/dns_server: 8.8.8.8/dns_server: {{ dns_server.stdout }}/g' {{ browbeat_dir }}/ansible/install/group_vars/all.yml
    - name: generate hosts file
      shell: |
          source /home/stack/stackrc
          ./generate_tripleo_hostfile.sh -l 
      args:
          chdir: "{{ browbeat_dir }}/ansible"
    - name: install browbeat
      shell: |
          cd /home/stack/browbeat/ansible
          ansible-playbook -i hosts install/browbeat.yml
      args:
          chdir: "{{ browbeat_dir }}/ansible"
