- hosts: localhost
  tasks:
      - name: load instackenv file
        include_tasks: tasks/load_instackenv.yml

      - name: setup infrared
        include_tasks: tasks/setup_infrared.yml

      - name: prepare inventory
        include_tasks: tasks/prepare_inventory.yml
        vars:
            infrared_hosts_dir: "{{ infrared_workspaces_dir }}/active"
            inventory_file_name: "hosts-updated"
