- hosts: localhost
  tasks:
      - name: install packages
        include_tasks: tasks/install_packages.yml

      - name: check if ssh key exists
        stat:
           path: "{{ ansible_ssh_key }}"
        register: sshkey

      - name:  Generate ssh key
        shell:
           ssh-keygen -q -N "" -f {{ ansible_ssh_key }}
        when: sshkey.stat.exists == False

      - name: load instackenv file
        include_tasks: tasks/load_instackenv.yml

      - name: setup infrared
        include_tasks: tasks/setup_infrared.yml

      - name: add localhost to inventory file
        add_host:
          name: "localhost"
          groups: "local"
          ansible_connection: "local"
