---
- hosts: undercloud
  gather_facts: yes
  tasks:
      # RHBZ 1756492
      - name: exclude ceph images
        lineinfile:
          path: /home/stack/containers-prepare-parameter.yaml
          insertafter: "- push_destination: true"
          line: '    excludes:'
        when: osp_release > 13
      - name: exclude ceph images
        lineinfile:
          path: /home/stack/containers-prepare-parameter.yaml
          insertafter: "    excludes:"
          line: '    - ceph'
        when: osp_release > 13
      - name: get tht version
        shell: |
          grep  "heat_template_version" /usr/share/openstack-tripleo-heat-templates/overcloud.j2.yaml | cut -d ':' -f2
        register: tht_version
      - name: set heat_template_version
        set_fact:
          heat_template_version: "{{ tht_version.stdout }}"
      - name: generate os-net-config-mappings.yaml
        template:
          src: "os-net-config-mappings.yaml.j2"
          dest: "/home/stack/os-net-config-mappings.yaml"

- hosts: localhost
  gather_facts: yes
  vars:
      instackenv_content: "{{ lookup('file', '{{ instackenv_file }}') | from_json }}"
  tasks:
      - name: Enable overcloud deployment with extra user defined templates
        block:
          - name: Check if the templates exist on the undercloud
            stat:
              path: "{{ item }}"
            register: env_files
            loop: "{{ extra_templates }}"
            delegate_to: "{{ undercloud_hostname }}"
            vars:
              ansible_python_interpreter: "{{ python_interpreter }}"
              ansible_user: "stack"

          - name: Copy files to undercloud if they do not exist
            copy:
              src: "{{ item.item }}"
              dest: "/home/stack/"
            loop: "{{ env_files.results }}"
            when: not item.stat.exists
            delegate_to: "{{ undercloud_hostname }}"
            vars:
              ansible_python_interpreter: "{{ python_interpreter }}"
              ansible_user: "stack"

          - name: Template out extra overcloud-templates file
            template:
              src: overcloud-templates.yml.j2
              dest: "{{ infrared_dir }}/plugins/tripleo-overcloud/vars/overcloud/templates/extra.yml"

        when: ( extra_templates is defined and extra_templates|length>0 ) or ( parameter_defaults is defined and parameter_defaults|length>0 )
      - name: Set compute count fact
        set_fact:
            compute_count: "{{ compute_count|default(instackenv_content.nodes|length - (controller_count|int + 1)) }}"

      - name: get nodes
        shell: |
            source ~/stackrc
            openstack baremetal node list -f value -c UUID
        register: nodes_uuids
        changed_when: false
        delegate_to: "{{ groups.undercloud|first }}"
        vars:
          ansible_python_interpreter: "{{ python_interpreter }}"
          ansible_user: "stack"

      - name: check registered nodes with requested node count
        debug:
           msg: "Less nodes {{ nodes_uuids.stdout_lines|length }} registered with ironic than requested {{ compute_count|int + controller_count|int }}. So we will be adjusting controller and compute count according to registered available nodes"
        when: nodes_uuids.stdout_lines|length < (compute_count|int + controller_count|int)

      - name: Adjust compute count
        set_fact:
            compute_count: "{{ compute_count|int - 1 }}"
        when: nodes_uuids.stdout_lines|length < (compute_count|int + controller_count|int)
        with_items: "{{ nodes_uuids }}"

      - name: fail when compute count is less than 1
        fail:
            msg: "Failing as compute count is less than 1"
        when: compute_count|int < 1
      - name: set network-backend option
        set_fact:
          network_backend: "{{ (osp_release|int > 14)|ternary('geneve', 'vxlan') }}"
      - name: run tripleo-overcloud deploy
        shell: |
            source .venv/bin/activate
            infrared tripleo-overcloud -vvv --version {{ osp_release }} --deployment-files {{ nic_configs }} --introspect no --tagging no --deploy yes --controller-nodes {{ controller_count }} --compute-nodes {{ compute_count }} --network-protocol ipv4 --network-backend {{ network_backend }} --public-network false &> overcloud_deploy.log
        args:
            chdir: "{{ infrared_dir }}"
        when: extra_templates is not defined and parameter_defaults is not defined

      - name: run tripleo-overcloud deploy with extra templates
        shell: |
            source .venv/bin/activate
            infrared tripleo-overcloud -vvv --version {{ osp_release }} --build {{ osp_puddle }}  --deployment-files {{ nic_configs }} --introspect no --tagging no --deploy yes --controller-nodes {{ controller_count }} --compute-nodes {{ compute_count }} --overcloud-templates {{ infrared_dir }}/plugins/tripleo-overcloud/vars/overcloud/templates/extra.yml --network-protocol ipv4 --network-backend {{ network_backend }} --public-network false &> overcloud_deploy.log
        args:
            chdir: "{{ infrared_dir }}"
        when: ( extra_templates is defined and extra_templates|length>0 ) or ( parameter_defaults is defined and parameter_defaults|length>0 )

- hosts: undercloud
  gather_facts: yes
  vars:
       external_interface: "{{ hostvars['localhost']['external_interface'] }}"
  tasks:
      - name: get ext_interface
        shell: |
          for i in /sys/class/net/*
          do
            udevcontent=`udevadm info -p $i --query property`
            if [[ $udevcontent =~ {{ external_interface }} ]]
            then
              ext_interface=`echo $i | cut -d '/' -f 5`
              break
            fi
          done
          echo $ext_interface
        register: ext_interface
      - name: set ext_iface
        set_fact:
          ext_iface: "{{ ext_interface.stdout }}"
      - name: create vlan interface on external interface
        vars:
            vlan_interface: "{{ ext_iface }}.{{ external_network_vlan_id }}"
        shell: |
            ip link add link {{ ext_iface }} name {{ vlan_interface }} type vlan id {{ external_network_vlan_id }}
            ip link set dev {{ ext_iface }} up
            ip link set dev {{ vlan_interface }} up
            ip a a {{ external_gateway }} brd {{ external_network_broadcast }} dev {{ vlan_interface }}
        become: true

      - name: masquerade on public interface
        shell: |
            iptables -t nat -A POSTROUTING -o {{ public_interface }} -j MASQUERADE
        become: true
