---
- hosts: undercloud
  become: yes
  become_user: stack
  tasks:
    - name: create nvme flavor
      shell: |
        source /home/stack/overcloudrc
        openstack flavor create --ram {{ nvme.flavor.ram }} --disk {{ nvme.flavor.disk }} --vcpus {{ nvme.flavor.vcpus }} --public {{ nvme.flavor.name }}
      changed_when: false
      ignore_errors: true
      when: nvme is defined

    - name: set pci passthough for flavor
      shell: |
        source /home/stack/overcloudrc
        openstack flavor set {{ nvme.flavor.name }} --property "pci_passthrough:alias"="nvme:1"
      changed_when: false
      when: nvme is defined

    - name: set public_net_name
      set_fact:
        public_net_name: "{{ public_net_name|default('public') }}"

    - name: create external network
      shell: |
        source /home/stack/overcloudrc
        neutron net-create --router:external=True --provider:network_type flat --provider:physical_network datacentre {{ public_net_name }}
      changed_when: false
      ignore_errors: true
      when: external_network_vlan_id is not defined

    - name: create external network
      shell: |
        source /home/stack/overcloudrc
        neutron net-create --router:external=True --provider:network_type vlan --provider:physical_network datacentre --provider:segmentation_id {{ external_network_vlan_id }} {{ public_net_name }}
      changed_when: false
      ignore_errors: true
      when: external_network_vlan_id is defined

    - name: set alloc_end
      vars:
        allocation_end: "{{ external_net_cidr | ipaddr('net') | ipaddr('-2') }}"
      set_fact:
        alloc_end: "{{ allocation_end.split('/')[0] }}"

    - name: create external subnet
      vars:
        gateway_address: "{{ external_gateway.split('/')[0] }}"
        alloc_start: "{{ ((external_allocation_pools_end | ipaddr('int')) + 1) | ipaddr }}"
      shell: |
        source /home/stack/overcloudrc
        neutron subnet-create --ip_version 4 --gateway {{ gateway_address }} --allocation-pool start={{ alloc_start }},end={{ alloc_end }} --disable-dhcp {{ public_net_name }} {{ external_net_cidr }}
      changed_when: false
      ignore_errors: true

