---
- hosts: undercloud
  become: yes
  become_user: stack
  tasks:
    - name: create nvme flavor
      shell: |
        source /home/stack/overcloudrc
        openstack flavor create --ram {{ nvme.flavor.ram }} --disk {{ nvme.flavor.disk }} --vcpus {{ nvme.flavor.vcpus }} --public {{ nvme.flavor.name }}
      changed_when: false
      ignore_errors: true
      when: nvme is defined
    - name: set pci passthough for flavor
      shell: |
        source /home/stack/overcloudrc
        openstack flavor set {{ nvme.flavor.name }} --property "pci_passthrough:alias"="nvme:1"
      changed_when: false
      when: nvme is defined

