---
- hosts: undercloud
  gather_facts: yes
  tasks:
    - name: create nvme flavor
      shell: |
        source overcloudrc
        openstack flavor create --ram {{ nvme.flavor.ram }} --disk {{ nvme.flavor.disk }} --vcpus {{ nvme.flavor.vcpus }} --public {{ nvme.flavor.name }}
        openstack flavor set {{ nvme.flavor.name }} --property "pci_passthrough:alias"="nvme:1"
      changed_when: false
      ignore_errors: true
      when: nvme is defined

