---
- hosts: localhost
  gather_facts: yes
  any_errors_fatal: true
  tasks:
      - name: set ifaces
        set_fact:
            ifaces: "{{ hostvars[groups.undercloud|first]['ifaces'] }}"
      - name: check hypervisors has three or more nics
        fail:
            msg: "hypervisor has less nics" 
        when: ifaces|length < 3
      - name: select nic-configs virt folder
        set_fact:
            virt: "{{ (ifaces|length == 3)|ternary('virt', 'virt_4nics') }}"
      - name: Ensure deployment folder nested structure exists
        copy:
            src: "{{ virt }}"
            dest: "{{ ansible_user_dir }}/"
      - name: set nic_configs
        set_fact:
            nic_configs: "{{ ansible_user_dir }}/{{ virt }}"
      - name: set ctlplane_interface
        set_fact:
            ctlplane_interface: "{{ hostvars[groups.undercloud|first]['ctlplane_interface'] }}"
      - name: replace nic names              
        replace:
            path: "{{ item.src }}"
            regexp: "nic1"
            replace: "{{ ctlplane_interface }}"
        with_filetree: '{{ nic_configs }}'
        when: item.state == 'file'
      - name: Replace other nic names with interface names
        include_tasks: tasks/prepare_interfaces.yml
        loop: "{{ ifaces }}"
        loop_control:
            index_var: iface_index
