---
- hosts: undercloud
  tasks:
      - name: install libselinux-python in undercloud
        shell: setenforce 0
        ignore_errors: true

- hosts: localhost
  tasks:
      - name: set compute_count
        set_fact:
            compute_count: "{{ json_file.nodes|length - (controller_count|int + 1) }}"
        when: compute_count is not defined
      - name: run tripleo-undercloud
        shell: |
            cd {{ infrared_dir }}
            source {{ infrared_dir }}/.venv/bin/activate
            infrared tripleo-undercloud -vv --version {{ osp_release }} --images-task rpm --config-options DEFAULT.local_interface={{ ctlplane_interface }} --config-options DEFAULT.local_ip=192.168.0.1/16 --config-options DEFAULT.undercloud_public_host=192.168.0.2 --config-options DEFAULT.undercloud_admin_host=192.168.0.3 --config-options DEFAULT.clean_nodes=True --config-options ctlplane-subnet.cidr=192.168.0.0/16 --config-options ctlplane-subnet.dhcp_start=192.168.3.1 --config-options ctlplane-subnet.dhcp_end=192.168.6.254 --config-options ctlplane-subnet.inspection_iprange=192.168.0.5,192.168.2.254 --config-options ctlplane-subnet.gateway=192.168.0.1 &> undercloud_install.log
        args:
            chdir: "{{ infrared_dir }}" 
      - name: run tripleo-overcloud
        shell: |
            source .venv/bin/activate
            infrared tripleo-overcloud -vvv --version {{ osp_release }} --instackenv-file {{ undercloud_instackenv_path }} --deployment-files {{ nic_configs }} --controller-nodes {{ controller_count }} --compute-nodes {{ compute_count }} --network-protocol ipv4 --network-backend vlan --public-network false --introspect yes --tagging yes --deploy yes &> overcloud_install.log
        args:
            chdir: "{{ infrared_dir }}" 
