- hosts: localhost
  vars:
    container_params: ""
  tasks:
      - name: get undercloud_local_interface
        shell: |
          for i in /sys/class/net/*
          do
            udevcontent=`udevadm info -p $i --query property`
            if [[ $udevcontent =~ {{ ctlplane_interface }} ]]
            then
              undercloud_local_interface=`echo $i | cut -d '/' -f 5`
              break
            fi
          done
          echo $undercloud_local_interface
        register: local_interface
        delegate_to: "{{ undercloud_hostname }}"
        vars:
          ansible_python_interpreter: "{{ python_interpreter }}"
          ansible_user: "stack"
        become: true

      - name: set undercloud_local_interface
        set_fact:
          undrecloud_local_interface: "{{ local_interface.stdout }}"
      - name: Setup undercloud.conf
        template:
            src: undercloud.conf.j2
            dest: "{{ undercloud_conf }}"
      - name: Set container params
        set_fact:
          container_params: "--registry-mirror {{ registry_mirror }} --registry-namespace {{ registry_namespace }}"
        when: osp_release > 13
      - name: run tripleo-undercloud
        shell: |
          source {{ infrared_dir }}/.venv/bin/activate
          infrared tripleo-undercloud -vv \
          --version {{ osp_release }} \
          --build {{ osp_puddle }} \
          --images-task rpm \
          --config-file {{ undercloud_conf }} {{ container_params }} &> undercloud_install.log
        args:
            chdir: "{{ infrared_dir }}"
        changed_when: false
