---
- name: create shiftstack project
  os_project:
    cloud: "overcloud"
    state: present
    name: "shiftstack"
    domain: default

- name: create user
  os_user:
    cloud: "overcloud"
    state: present
    name: "shiftstack_user"
    password: "redhat"
    domain: default

- name: add member roll
  os_user_role:
    cloud: "overcloud"
    state: present
    project: "shiftstack"
    user: "shiftstack_user"
    role: "member"

- name: add swiftoperator role
  os_user_role:
    cloud: "overcloud"
    state: present
    project: "shiftstack"
    user: "shiftstack_user"
    role: "swiftoperator"
