---
- name: Install dependencies
  package:
    name: "{{ item }}"
    state: installed
  loop:
      - git
      - gcc
      - libffi-devel
      - python-virtualenv
      - libselinux-python
      - python30-virtualenv
      - python3-libselinux
  become: true
  failed_when: false

- name: clone infrared
  git:
      repo: "https://github.com/redhat-openstack/infrared"
      dest: "{{ infrared_dir }}"
      force: yes

- name: Add all plugins
  shell: |
      git fetch "https://review.gerrithub.io/redhat-openstack/infrared" refs/changes/76/463576/2 && git checkout FETCH_HEAD
      virtualenv .venv && source .venv/bin/activate
      pip install --upgrade pip
      pip install --upgrade setuptools
      pip install .
      rm -rf {{ ansible_user_dir }}/.infrared
      infrared plugin add all
      infrared workspace create {{ workspace_name }}
      infrared workspace checkout {{ workspace_name }}
  args:
    chdir: "{{ infrared_dir }}"
  changed_when: false
  vars:
      workspace_name: "{{ 'workspace_' + ansible_date_time.date + '_' + ansible_date_time.time|string|replace(':','-') }}"
